### ISSUE TITLE
python line incomplete?

### ISSUE THREAD

**Issue by cslamo** [ignasrum/hocort#3]
Is this line alright? I get errors that that can be fixed by completing seq1=seq1 and out1=out1 and idz=idx, however after this I get the following error:

TypeError: Run() missing one required positional argument : 'self'

**Comment by ignasrum** [comment]
You probably forgot to make an instance of the class. 

```
from hocort.pipelines.bowtie2 import Bowtie2

returncode = Bowtie2().run(...)
```
