### ISSUE TITLE
ModuleNotFoundError: No module named 'hocort.aligners.aligner'

### ISSUE THREAD

**Issue by shaodongyan** [ignasrum/hocort#4]
I used conda install then use . But i meet "ModuleNotFoundError: No module named 'hocort.aligners.aligner'

**Comment by ignasrum** [comment]
Sorry for that, I am currently having problems with the conda recipe. You can try using an older version which should be working. 

`conda install hocort=1.0.0 -c conda-forge -c bioconda`

**Comment by ignasrum** [comment]
I updated HoCoRT to 1.2.1. The issue should be fixed now.
