### ISSUE TITLE
Is the paper under publishment?

### ISSUE THREAD

**Issue by HuoJnx** [ignasrum/hocort#5]
Hey, thank you very much for your work, it‘s no doubt save my life.

But when I want to cite the paper in my own work I find it's on BioRxiv, so may I ask if you have plan to publish it on a journal with impact factor this year?

Thank you very much!

**Comment by ignasrum** [comment]
Hello!

Thank you for the positive feedback!
Currently the paper is only on bioRxiv, but we will be publishing it in a peer-reviewed journal later this year.

**Comment by ignasrum** [comment]
Hello again!

The paper is now published in BMC Bioinformatics:
[https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-023-05492-w](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-023-05492-w)

**Comment by HuoJnx** [comment]
Good news and congratulation! Now I can cite it for further research, thanks a lot for your hard work!
