### ISSUE TITLE
How to use the un_conc mode in bowtie2?

### ISSUE THREAD

**Issue by HuoJnx** [ignasrum/hocort#6]
Hello, I have read your paper and find that Bowtie2 with un_conc mode will get the best precision.
<img width="774" alt="image" src="https://user-images.githubusercontent.com/40828030/233139953-96c28260-ae60-4b56-ab88-a47e1eba73f8.png">

Do you know how can I use the un_conc mode in hocort? From the document, It seems that we can't simply set it by -c argument?

**Comment by ignasrum** [comment]
For the Bowtie2 -un-conc mode I would use the following command outside of HoCoRT:
`bowtie2 -x index/prefix --end-to-end -p numberOfThreads -1 input_R1.fq -2 input_R2.fq --un-conc-gz bowtie2_output > /dev/null`
or if you want output in the terminal:
`bowtie2 -x index/prefix --end-to-end -p numberOfThreads -1 input_R1.fq -2 input_R2.fq --un-conc-gz bowtie2_output`

**Comment by HuoJnx** [comment]
> For the Bowtie2 -un-conc mode I would use the following command outside of HoCoRT: `bowtie2 -x index/prefix --end-to-end -p numberOfThreads -1 input_R1.fq -2 input_R2.fq --un-conc-gz bowtie2_output > /dev/null` or if you want output in the terminal: `bowtie2 -x index/prefix --end-to-end -p numberOfThreads -1 input_R1.fq -2 input_R2.fq --un-conc-gz bowtie2_output`

Got it, thanks for your help!
