### ISSUE TITLE
ERR: does not exist or is not a Bowtie 2 index

### ISSUE THREAD

**Issue by bark9299** [ignasrum/hocort#7]
I am running hocort version 1.2.2 on python 3.9.13 with linux. I am trying to run  the command ` hocort map bowtie2 -x /hdd/2/elyse/microbiome/Sweden_MSU_metagenomics_shotgun/20240209_DNASeq_PE150/combined_pipefish_genomes/ -i RM4_BP_S14_L003_R1_001.fastq.gz RM4_BP_S14_L003_R2_001.fastq.gz -o RM4_1_out.fastq RM4_2_out.fastq` where my directory `combined_pipefish_genomes` has the bowtie indexes made with `hocort index bowtie2 `.  Everytime I run the mapping command, the error is :
`(ERR): "/hdd/2/elyse/microbiome/Sweden_MSU_metagenomics_shotgun/20240209_DNASeq_PE150/combined_pipefish_genomes/" does not exist or is not a Bowtie 2 index
Exiting now ...
Failed to read header for "-"
Pipeline exited with returncode: 1`

Why is this command not running properly? I have directed hocort to the bowtie2 indexes so I'm not sure what to do now.

**Comment by ignasrum** [comment]
Hello! 

The index parameter (-x) of the map command requires input in the following format; directory/basename. 

Therefore, your input would be something like this `/hdd/2/elyse/microbiome/Sweden_MSU_metagenomics_shotgun/20240209_DNASeq_PE150/combined_pipefish_genomes/basename` where the .bt2 files inside the combined_pipefish_genomes directory start with «basename».

**Comment by bark9299** [comment]
Thank you so much for your quick reply! sorry I didn't catch that.
